services:
  postgres:
    image: postgres:15
    container_name: nyc_postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  jupyter:
    image: jupyter/base-notebook
    container_name: nyc_jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      JUPYTER_TOKEN: taxi
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: nyc_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      



volumes:
  pgdata:
  pgadmin_data:

